---

- name: Install Bosun Agent (APT)
  apt: pkg=bosun-scollector state=present upgrade={{ _bosun_agent.upgrade }}
  when: _bosun_agent.install|bool

- name: Ensure /usr/local/sbin Directory exists
  file: path=/usr/local/sbin state=directory owner=root group=root mode=0755

- name: Install Bosun Agent (download)
  get_url: url={{ _bosun_agent.download_url|default("no url specified") }} dest=/usr/local/sbin/scollector force={{ _bosun_agent.upgrade }}
  register: downloaded
  when: _bosun_agent.install|lower == "download"

- name: Set File Permissions if Downloaded
  file: path=/usr/local/sbin/scollector owner=root group=root mode=0755
  when: downloaded|changed or _bosun_agent.upgrade|bool

- name: Copy Systemd Unit File
  copy: src=etc/systemd/system/scollector.service dest=/etc/systemd/system/scollector.service owner=root group=root mode=0644
  when: _bosun_agent.init|lower == "systemd" and (downloaded|changed or _bosun_agent.upgrade|bool)

- name: Create SCollector Configuration Directory
  file: path=/etc/scollector state=directory owner=root group=root mode=0755

- name: Enable Bosun Agent
  service: name=scollector enabled=yes

- name: Create bosun-agent logrotate configuration
  copy: src=etc/logrotate.d/scollector dest=/etc/logrotate.d/scollector owner=root group=root mode=0644
  when: _bosun_agent.init|lower == "upstart"

- name: Ensure /usr/local/bin Directory exists
  file: path=/usr/local/bin state=directory owner=root group=root mode=0755

- name: Create CLI datum sender
  template: src=usr/local/bin/post_datum_to_bosun.py.j2 dest=/usr/local/bin/post_datum_to_bosun.py owner=root group=root mode=0755

- set_fact:
    curl_auth: "-u {{ _bosun_agent.server.user }}:{{ _bosun_agent.server.password }}"
  when: _bosun_agent.server.user is defined and _bosun_agent.server.password is defined

- name: Configure scollector
  template: src=etc/bosun/scollector.conf.j2 dest=/etc/scollector/scollector.toml owner=root group=root mode=0640
  notify:
    - Restart scollector

